trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: XamarinAndroid@1
  displayName: 'Build Xamarin Android App'
  inputs:
    projectFile: '**/*.csproj'
    outputDirectory: '$(build.artifactStagingDirectory)/apk'
    configuration: 'Release'
