name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . -f Dockerfile -t my-image-name:$TIMESTAMP
